name: progress_loader_overlay_example
description: Demo app for the progress_loader_overlay package.
publish_to: 'none'

version: 3.0.2+5

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  progress_loader_overlay:
    path: ../