name: progress_loader_overlay
description: A flutter package to show an easy to use and fully customizable progress loader as an overlay.
version: 3.0.3
homepage: https://github.com/quentinleguennec/flutter-progress-loader-overlay
issue_tracker: https://github.com/quentinleguennec/flutter-progress-loader-overlay/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter